### PR TITLE
Hf contact buttons

### PR DESCRIPTION
**Pull request by martypowell**
addresses #621 

- Fixes issue where cards loaded event was not being fired in all browsers
- Converted Contact button to a button to be more semantic and fix issue where button was selected, the page would scroll

@danfox01 @tmccoy529 fyi

### CODE REVIEW

**Comment by danfox01** [comment]
OK... can you please let me know for sure and we can commence with the hammering.

**Comment by tmccoy529** [comment]
Fixed a style issue with the button displaying a shadow when you clicked it. May need to be reviewed though it doesn't appear to be requesting it.

@martypowell

**Comment by tmccoy529** [comment]
@danfox01 Marty and I have moved these changes to dev and they are ready to be tested.

**Comment by tmccoy529** [comment]
@jdomasky @martypowell @ danfox01 I had not moved over the high contrast file to SE. This has been moved and ready for retest.

**Comment by jdomasky** [comment]
Thanks, @tmccoy529. Retesting went well. Everything looks great now! @martypowell @danfox01

**Comment by tmccoy529** [comment]
@danfox01 we will do a hot fix on Monday for this. I'd like to have Marty around when I do this to make sure I don't do anything wrong and bring down prod.

**Comment by danfox01** [comment]
@tmccoy529, haha I don't want that either. Let's touch base Monday morning and schedule a time to do this. I'll want @jdomasky available to test prod too. Thanks!

**Comment by danfox01** [comment]
Hey gents, when do we want to tackle this release? If it's today, I want to make sure we get it in with enough time to allow @jdomasky to test.

**Pull request merged**
